import { Metadata } from "next";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";

import "@/css/globals.css";
import "@mantine/core/styles.css";

import ParentProps from "@/types/general/ParentProps";
import Providers from "@/components/Providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
} satisfies Metadata as Metadata;

const RootLayout = ({ children }: ParentProps) => (
    <html {...mantineHtmlProps}>
        <head>
            <ColorSchemeScript />
        </head>
        <body className="antialiased">
            <Providers>
                {children}
            </Providers>
        </body>
    </html>
);

export default RootLayout;